export default [
  {
    id: 1,
    diameter: 50,
    numberTeeth: 4,
    type: "FRESA_SPIANATURA",
    nameDescription: "Fresa spianatrice 50mm",
    angle: 90,
    length: 100,
    feedPerTeeth: 0.2,
    spindleSpeed: 3000,
    needsCoolant: true,
    rotationDirection: "COUNTERCLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 2,
    diameter: 8,
    numberTeeth: 4,
    type: "PUNTA_ELICOIDALE",
    nameDescription: "Punta elicoidale 8mm",
    angle: 118,
    length: 60,
    feedPerTeeth: 0.1,
    spindleSpeed: 8000,
    needsCoolant: false,
    rotationDirection: "CLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 3,
    diameter: 10,
    numberTeeth: 2,
    type: "MASCHIATORE",
    nameDescription: "Maschiatura M10",
    angle: 90,
    length: 60,
    feedPerTeeth: 0.01,
    spindleSpeed: 1500,
    needsCoolant: true,
    rotationDirection: "CLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 4,
    diameter: 20,
    numberTeeth: 4,
    type: "FRESA_SPIANATURA",
    nameDescription: "Fresa spianatrice 20mm",
    angle: 90,
    length: 60,
    feedPerTeeth: 0.1,
    spindleSpeed: 5000,
    needsCoolant: true,
    rotationDirection: "CLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 5,
    diameter: 3,
    numberTeeth: 2,
    type: "PUNTA_ELICOIDALE",
    nameDescription: "Punta elicoidale 3mm",
    angle: 130,
    length: 30,
    feedPerTeeth: 0.05,
    spindleSpeed: 12000,
    needsCoolant: false,
    rotationDirection: "COUNTERCLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 6,
    diameter: 12,
    numberTeeth: 4,
    type: "FRESA_SPIANATURA",
    nameDescription: "Fresa spianatrice 12mm",
    angle: 90,
    length: 40,
    feedPerTeeth: 0.15,
    spindleSpeed: 4000,
    needsCoolant: true,
    rotationDirection: "CLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 7,
    diameter: 5,
    numberTeeth: 2,
    type: "PUNTA_ELICOIDALE",
    nameDescription: "Punta elicoidale 5mm",
    angle: 118,
    length: 40,
    feedPerTeeth: 0.08,
    spindleSpeed: 10000,
    needsCoolant: true,
    rotationDirection: "COUNTERCLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
  {
    id: 8,
    diameter: 8,
    numberTeeth: 4,
    type: "FRESA_SPIANATURA",
    nameDescription: "Fresa spianatrice 8mm",
    angle: 90,
    length: 30,
    feedPerTeeth: 0.05,
    spindleSpeed: 6000,
    needsCoolant: false,
    rotationDirection: "CLOCKWISE",
    compensation: {
      x: 0,
      y: 0,
      z: 0,
    },
  },
];
